FROM node:25 AS build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build:production

FROM nginx:alpine
COPY --from=build /app/dist/storage-service-client/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
